# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ESL', [dirname(__file__)])
        except ImportError:
            import _ESL
            return _ESL
        if fp is not None:
            try:
                _mod = imp.load_module('_ESL', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ESL = swig_import_helper()
    del swig_import_helper
else:
    import _ESL
del version_info

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

class ESLevent:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ESLevent, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ESLevent, name)
    __repr__ = _swig_repr
    __swig_setmethods__["event"] = _ESL.ESLevent_event_set
    __swig_getmethods__["event"] = _ESL.ESLevent_event_get
    __swig_setmethods__["serialized_string"] = _ESL.ESLevent_serialized_string_set
    __swig_getmethods__["serialized_string"] = _ESL.ESLevent_serialized_string_get
    __swig_setmethods__["mine"] = _ESL.ESLevent_mine_set
    __swig_getmethods__["mine"] = _ESL.ESLevent_mine_get

    def __init__(self, *args):
        this = _ESL.new_ESLevent(*args)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _ESL.delete_ESLevent
    __del__ = lambda self: None

    def serialize(self, format=None):
        return _ESL.ESLevent_serialize(self, format)

    def setPriority(self, *args):
        return _ESL.ESLevent_setPriority(self, *args)

    def getHeader(self, header_name, idx=-1):
        return _ESL.ESLevent_getHeader(self, header_name, idx)

    def getBody(self):
        return _ESL.ESLevent_getBody(self)

    def getType(self):
        return _ESL.ESLevent_getType(self)

    def addBody(self, value):
        return _ESL.ESLevent_addBody(self, value)

    def addHeader(self, header_name, value):
        return _ESL.ESLevent_addHeader(self, header_name, value)

    def pushHeader(self, header_name, value):
        return _ESL.ESLevent_pushHeader(self, header_name, value)

    def unshiftHeader(self, header_name, value):
        return _ESL.ESLevent_unshiftHeader(self, header_name, value)

    def delHeader(self, header_name):
        return _ESL.ESLevent_delHeader(self, header_name)

    def firstHeader(self):
        return _ESL.ESLevent_firstHeader(self)

    def nextHeader(self):
        return _ESL.ESLevent_nextHeader(self)
ESLevent_swigregister = _ESL.ESLevent_swigregister
ESLevent_swigregister(ESLevent)

class ESLconnection:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ESLconnection, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ESLconnection, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _ESL.new_ESLconnection(*args)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _ESL.delete_ESLconnection
    __del__ = lambda self: None

    def socketDescriptor(self):
        return _ESL.ESLconnection_socketDescriptor(self)

    def connected(self):
        return _ESL.ESLconnection_connected(self)

    def getInfo(self):
        return _ESL.ESLconnection_getInfo(self)

    def send(self, cmd):
        return _ESL.ESLconnection_send(self, cmd)

    def sendRecv(self, cmd):
        return _ESL.ESLconnection_sendRecv(self, cmd)

    def api(self, cmd, arg=None):
        return _ESL.ESLconnection_api(self, cmd, arg)

    def bgapi(self, cmd, arg=None, job_uuid=None):
        return _ESL.ESLconnection_bgapi(self, cmd, arg, job_uuid)

    def sendEvent(self, send_me):
        return _ESL.ESLconnection_sendEvent(self, send_me)

    def sendMSG(self, send_me, uuid=None):
        return _ESL.ESLconnection_sendMSG(self, send_me, uuid)

    def recvEvent(self):
        return _ESL.ESLconnection_recvEvent(self)

    def recvEventTimed(self, ms):
        return _ESL.ESLconnection_recvEventTimed(self, ms)

    def filter(self, header, value):
        return _ESL.ESLconnection_filter(self, header, value)

    def events(self, etype, value):
        return _ESL.ESLconnection_events(self, etype, value)

    def execute(self, app, arg=None, uuid=None):
        return _ESL.ESLconnection_execute(self, app, arg, uuid)

    def executeAsync(self, app, arg=None, uuid=None):
        return _ESL.ESLconnection_executeAsync(self, app, arg, uuid)

    def setAsyncExecute(self, val):
        return _ESL.ESLconnection_setAsyncExecute(self, val)

    def setEventLock(self, val):
        return _ESL.ESLconnection_setEventLock(self, val)

    def disconnect(self):
        return _ESL.ESLconnection_disconnect(self)
ESLconnection_swigregister = _ESL.ESLconnection_swigregister
ESLconnection_swigregister(ESLconnection)


def eslSetLogLevel(level):
    return _ESL.eslSetLogLevel(level)
eslSetLogLevel = _ESL.eslSetLogLevel
# This file is compatible with both classic and new-style classes.


